JTBDonDjango/urls.py
# from django.contrib import admin
from django.urls import path
from app01.views import admin, agents, flows, jtbd, cases, sse, user

urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('login/', user.login, name='login'),
    path('sse/start/', sse.start_task, name='start_task'),
    path('sse/stream/', sse.sse_stream, name='sse_stream'),
    path('sse/test/', sse.sse_test),
    path('', jtbd.homepage),
    path('jtbd/opencase/', jtbd.opencase, name='opencase'),
    path('jtbd/work/', jtbd.work),
    path('jtbd/output/', jtbd.output),
    path('jtbd/listcase/', jtbd.listcase, name='listcase'),
    path('jtbd/pincase/', jtbd.pincase, name='pincase'),
    path('jtbd/delcase/', jtbd.delcase, name='delcase'),

    # 运行监控
    path('case/list/', cases.case_list),
    path('case/<int:cid>/detail/', cases.case_detail),
    # Agent管理
    path('agent/list/', agents.agent_list),
    path('agent/add/', agents.agent_add),
    path('agent/<int:nid>/edit/', agents.agent_edit),
    path('agent/<int:nid>/delete/', agents.agent_delete),

    # Flow管理
    path('flow/list/', flows.flow_list),
    path('flow/add/', flows.flow_add),
    path('flow/delete/', flows.flow_delete),
    path('flow/edit/', flows.flow_edit),
    path('flow/detail/', flows.flow_detail),
    path('step/<int:fid>/list/', flows.step_list),
    path('step/add/', flows.step_add),
    path('step/edit/', flows.step_edit),
    path('step/delete/', flows.step_delete),
    path('step/detail/', flows.step_detail),

    # 登录管理
    path('admin/login/', admin.login),
    path('admin/logout/', admin.logout),
    path('captcha/', admin.captcha_image, name='captcha'),

    path('login/', user.login),
    path('logout/', user.logout),
    path('register/', user.register),

]

app01/models.py
from django.db import models
from django.db.models.manager import Manager


# Create your models here.

class Users(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username


class Agents(models.Model):
    name = models.CharField(verbose_name='角色名称', max_length=32)
    description = models.CharField(verbose_name='简介', max_length=64)
    user_prompt = models.TextField(verbose_name='用户提示词')
    system_prompt = models.TextField(verbose_name='系统提示词')
    output = models.CharField(verbose_name='输出变量', max_length=32)

    def __str__(self):
        return self.name

class Inputs(models.Model):
    name = models.CharField(verbose_name='输入变量名称', max_length=32)
    agent = models.ForeignKey(Agents, on_delete=models.CASCADE)


class Cases(models.Model):
    product = models.CharField(verbose_name='产品', max_length=128)
    info = models.TextField(verbose_name='产品说明')
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    core_job = models.CharField(verbose_name='核心任务', max_length=128, null=True, blank=True)
    job_map = models.CharField(verbose_name='任务地图', max_length=512, null=True, blank=True)
    start_time = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_time = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)
    delta = models.FloatField(verbose_name='用时（秒）', null=True, blank=True)
    closed = models.BooleanField(verbose_name='完成', default=False)
    pinned = models.BooleanField(verbose_name='置顶', default=False)
    pinned_time = models.DateTimeField(verbose_name='置顶时间', null=True, blank=True)

    def __str__(self):
        return self.product


class Opportunities(models.Model):
    oppo = models.CharField(verbose_name='机会描述', max_length=128)
    type_choices = (
        (1, 'related_job'),
        (2, 'desired_outcome'),
        (3, 'constrain'),
    )
    type = models.SmallIntegerField(verbose_name='机会类型', choices=type_choices)
    customer = models.CharField(verbose_name='目标客户', max_length=128)
    solution = models.CharField(verbose_name='针对性方案', max_length=512)
    slogan = models.CharField(verbose_name='宣传口号', max_length=128)
    case = models.ForeignKey(Cases, on_delete=models.CASCADE)


class Flows(models.Model):
    name = models.CharField(verbose_name='子流程', max_length=32)
    index = models.IntegerField(verbose_name='流程序号')
    description = models.CharField(verbose_name='简介', max_length=128)
    parent = models.ForeignKey('self',
                               on_delete=models.CASCADE,
                               verbose_name='父级',
                               null=True,
                               blank=True,
                               related_name='children')

    def __str__(self):
        return self.name


class Steps(models.Model):
    index = models.IntegerField(verbose_name='步骤序号')
    agent = models.ForeignKey(Agents, to_field='id', on_delete=models.CASCADE)
    flow = models.ForeignKey(Flows, to_field='id', on_delete=models.CASCADE)


class Contexts(models.Model):
    content = models.TextField(verbose_name='上下文')
    flow = models.ForeignKey(Flows, on_delete=models.CASCADE)
    case = models.ForeignKey(Cases, on_delete=models.CASCADE)

class Admin(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

class StepTimer(models.Model):
    case = models.ForeignKey(Cases, on_delete=models.CASCADE)
    step = models.ForeignKey(Steps, on_delete=models.CASCADE)
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    delta = models.FloatField(verbose_name='用时（秒）')

app01/utils/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from app01 import models
from app01.utils.bootstrap import BootstrapModelForm, BootstrapStyle
from app01.utils.encrypt import md5

# class UserModelForm(BootstrapModelForm):
#     class Meta:
#         model = models.UserInfo
#         fields = ['name', 'gender', 'password', 'age', 'account', 'create_time', 'depart']
#
# class NumModelForm(BootstrapModelForm):
#     mobile = forms.CharField(
#         label='手机号',
#         validators=[RegexValidator(r'^1[3-9]\d{9}$', '手机号码格式错误'), ],
#         widget=forms.TextInput(attrs={'class': 'form-control'}),
#     )
#
#     class Meta:
#         model = models.PrettyNum
#         fields = ['mobile', 'price', 'level', 'status']
#         # fields = "__all__"
#         # exclude = ['price']
#
#     def clean_mobile(self):
#         txt_mobile = self.cleaned_data['mobile']
#         exists = models.PrettyNum.objects.filter(mobile=txt_mobile).exists()
#         if exists:
#             raise ValidationError('手机号已存在')
#         return txt_mobile

# class NumEditModelForm(BootstrapModelForm):
#     mobile = forms.CharField(
#         validators=[RegexValidator(r'^1[3-9]\d{9}$', '手机号码格式错误'), ],
#         label='手机号',
#         widget=forms.TextInput(attrs={'class': 'form-control'}),
#     )
#
#     class Meta:
#         model = models.PrettyNum
#         fields = ['mobile', 'price', 'level', 'status']
#         # fields = "__all__"
#         # exclude = ['price']
#
#     def clean_mobile(self):
#         txt_mobile = self.cleaned_data['mobile']
#         exists = models.PrettyNum.objects.exclude(id=self.instance.pk).filter(mobile=txt_mobile).exists()
#         if exists:
#             raise ValidationError('手机号已存在')
#         return txt_mobile

# class AdminModelForm(BootstrapModelForm):
#     confirm_password = forms.CharField(
#         label='确认密码',
#         widget=forms.PasswordInput(render_value=True),
#     )
#     class Meta:
#         model = models.Admin
#         fields = ['username', 'password', 'confirm_password']
#         widgets = {
#             'password': forms.PasswordInput(render_value=True),
#         }
#
#     def clean_password(self):
#         password = self.cleaned_data['password']
#         return md5(password)
#
#     def clean_confirm_password(self):
#         confirm_password = md5(self.cleaned_data['confirm_password'])
#         password = self.cleaned_data['password']
#
#         if password != confirm_password:
#             raise ValidationError('密码不一致')
#
#         return confirm_password
#
# class AdminEditModelForm(BootstrapModelForm):
#     class Meta:
#         model = models.Admin
#         fields = ['username']

class AdminResetModelForm(BootstrapModelForm):
    confirm_password = forms.CharField(
        label='确认密码',
        widget=forms.PasswordInput(render_value=True),
    )

    class Meta:
        model = models.Admin
        fields = ['password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        md5_pwd = md5(password)
        exists = models.Admin.objects.filter(id=self.instance.pk, password=md5_pwd).exists()
        if exists:
            raise ValidationError('不能重复原密码')
        return md5_pwd

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = md5(self.cleaned_data.get('confirm_password'))
        if not password:
            return confirm_password
        if password != confirm_password:
            raise ValidationError('密码不一致')
        return confirm_password


class AgentAddForm(BootstrapModelForm):
    class Meta:
        model = models.Agents
        fields = ['name', 'description', 'system_prompt', 'user_prompt', 'output']

    def clean_name(self):
        name = self.cleaned_data['name']
        exists = models.Agents.objects.filter(name=name).exists()
        if exists:
            raise ValidationError('Agent名称不能重复')
        return name


class AgentEditForm(BootstrapModelForm):
    # Agent名称不能修改
    # name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    class Meta:
        model = models.Agents
        fields = ['name', 'description', 'system_prompt', 'user_prompt', 'output']

class FlowAddForm(BootstrapModelForm):
    class Meta:
        model = models.Flows
        fields = '__all__'

class StepEditForm(BootstrapModelForm):
    class Meta:
        model = models.Steps
        fields = ['index', 'agent']

    def clean_index(self):
        index = self.cleaned_data['index']
        fid = self.instance.flow_id
        exists = models.Steps.objects.exclude(id=self.instance.pk).filter(flow_id=fid, index=index).exists()
        if exists:
            raise ValidationError('序号不能重复')
        return index

class StepAddForm(BootstrapModelForm):
    class Meta:
        model = models.Steps
        fields = ['index', 'agent']

    def clean_index(self):
        index = self.cleaned_data['index']
        fid = self.instance.flow_id
        exists = models.Steps.objects.filter(flow_id=fid, index=index).exists()
        if exists:
            raise ValidationError('序号不能重复')
        return index

class LoginForm(BootstrapStyle, forms.Form):
    username = forms.CharField(
        label='用户名',
        widget=forms.TextInput,
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput,
    )
    captcha = forms.CharField(
        label='验证码',
        max_length=4,
    )
    def clean_password(self):
        password = self.cleaned_data.get('password')
        return md5(password)

class RegisterForm(BootstrapStyle, forms.ModelForm):
    password2 = forms.CharField(
        label='确认密码',
        widget=forms.PasswordInput,
    )
    captcha = forms.CharField(
        label='验证码',
        max_length=4,
    )

    class Meta:
        model = models.Users
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise ValidationError('密码不一致')
        return cd['password2']

app01/views/admin.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from app01.utils.forms import LoginForm
from app01 import models
from app01.utils.captcha import generate_captcha

def captcha_image(request):
    image_bytes, code = generate_captcha()
    request.session['captcha'] = code.upper()
    request.session.set_expiry(60)
    return HttpResponse(image_bytes, content_type='image/png')
def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'admin_login.html', {'form': form})

    form = LoginForm(request.POST)
    if form.is_valid():
        # 下面语句使用pop把captcha从cleaned_data中删除，以便剩下的cleaned_data用于数据库查询
        if form.cleaned_data.pop('captcha').upper() != request.session.get('captcha').upper():
            form.add_error('captcha', '验证码错误')
            return render(request, 'admin_login.html', {'form': form})

        # 去掉captcha的cleaned_data可以直接用于数据库查询
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error('password', '用户名或密码错误')
            return render(request, 'admin_login.html', {'form': form})

        # 密码正确，设置cookie
        request.session['info'] = { 'role': 'admin', 'id': admin_object.id, 'username': admin_object.username }
        request.session.set_expiry(60*60*24)
        return redirect('/agent/list/')
    return render(request, 'admin_login.html', {'form': form})

def logout(request):
    print('admin')
    request.session.clear()
    return redirect('/admin/login/')

app01/views/agents.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.forms import AgentAddForm, AgentEditForm


def agent_list(request):
    queryset = models.Agents.objects.all()
    return render(request, 'agent_list.html', {'queryset': queryset})


def agent_add(request):
    title = '新建Agent'
    if request.method == "GET":
        form = AgentAddForm()
        return render(request, 'agent_change.html', {'form': form, 'title': title})

    form = AgentAddForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('/agent/list/')
    return render(request, 'agent_change.html', {'form': form, 'title': title})

def agent_edit(request, nid):
    row_object = models.Agents.objects.filter(id=nid).first()

    if not row_object:
        return redirect('/agent/list/')

    title = '编辑Agent'

    if request.method == "GET":
        form = AgentEditForm(instance=row_object)
        return render(request, 'agent_change.html', {'form': form, 'title': title})

    form = AgentEditForm(request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/agent/list/')
    return render(request, 'agent_change.html', {'form': form, 'title': title})

def agent_delete(request, nid):
    models.Agents.objects.filter(id=nid).delete()
    return redirect('/agent/list/')

app01/views/cases.py
import json

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from app01 import models
from app01.utils.forms import FlowAddForm, StepAddForm, StepEditForm


def case_list(request):
    queryset = models.Cases.objects.all().order_by('-id')
    return render(request, 'case_list.html', {'queryset': queryset})

def case_detail(request, cid):
    # cid = request.GET.get('cid')
    case_data = models.Cases.objects.filter(id=cid).first()

    flow_data_list = []
    flow_index_list = models.Flows.objects.order_by('index').values_list('index', flat=True).distinct()
    for flow_index in flow_index_list:
        flows = models.Flows.objects.filter(index=flow_index).order_by('index')
        for flow in flows:
            row_object = models.Contexts.objects.filter(flow_id=flow.id, case_id=cid).first()
            context = json.loads(row_object.content)
            context = json.dumps(context, ensure_ascii=False, indent=2)
            steps = models.Steps.objects.filter(flow_id=flow.id).order_by('index')
            for step in steps:
                timer = models.StepTimer.objects.filter(case_id=cid, step_id=step.id).first()
                if timer:
                    step.start_time = timer.start_time
                    step.end_time = timer.end_time
                    step.delta = timer.delta
            flow_data = {
                'name': flow.name,
                'steps': steps,
                'context': context,
            }
            flow_data_list.append(flow_data)


    return render(request, 'case_detail.html', {'case_data': case_data, 'flow_data_list': flow_data_list})

app01/templates/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="/static/img/bitbug_favicon.ico">
    <title>管理员登录</title>
    <link href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}" rel="stylesheet">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 6px;
            box-shadow: 5px 5px 20px #aaaaaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 200px;
            padding: 20px 40px;
        }

        .account h1 {
            text-align: center;
            margin-top: 10px;
        }

        .captcha-img {
            cursor: pointer;
            height: 40px;
            border: 1px solid #ccc;
        }
    </style>
</head>
<body>
<div class="account">
    <h1>管理员登录</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red">{{ form.username.errors }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red">{{ form.password.errors }}</span>
        </div>
        <div class="form-group">
            <label>验证码</label>
            <div class="row">
                <div class="col-md-7">
                    {{ form.captcha }}
                    <span style="color: red">{{ form.captcha.errors }}</span>
                </div>
                <div class="col-md-5">
                    <img class="captcha-img" src="{% url 'captcha' %}">
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">登 录</button>
    </form>
</div>
<script>
    document.querySelector('.captcha-img').onclick = function () {
        this.src = "{% url 'captcha' %}?t=" + Date.now();
    };
    document.querySelector('#id_captcha').addEventListener('keydown', function (e) {
        if (e.key === 'Enter') {
            e.preventDefault();
            document.querySelector('.captcha-img').click();
        }
    });
</script>
</body>
</html>

app01/templates/agent_change.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">{{ title }}</div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label for="exampleInputEmail1">{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true" style="margin-right: 5px"></span>
                        提 交
                    </button>
                    <a class="btn btn-default" href="/agent/list/">
                        <span class="glyphicon glyphicon-home" aria-hidden="true" style="margin-right: 5px"></span>
                        返回
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        // 把系统提示词和用户提示词的文本框高度设置为自适应内容
        function autoResize(textarea) {
            textarea.style.height = 'auto';
            textarea.style.height = (textarea.scrollHeight + 2) + 'px';
        }

        // 监控系统提示词文本框的输入和拷贝事件
        document.querySelectorAll('#id_system_prompt').forEach(textarea => {
            autoResize(textarea);
            textarea.addEventListener('input', function () {
                autoResize(this);
            });
            textarea.addEventListener('paste', function (e) {
                setTimeout(() => autoResize(this), 0);
            });
        });
        // 监控用户提示词文本框的输入和拷贝事件
        document.querySelectorAll('#id_user_prompt').forEach(textarea => {
            autoResize(textarea);
            textarea.addEventListener('input', function () {
                autoResize(this);
            });
            textarea.addEventListener('paste', function (e) {
                setTimeout(() => autoResize(this), 0);
            });
        });

        // 把Agent角色名称文本框设为只读，禁止编辑
        function toggleReadOnly() {
            const input = document.getElementById('id_name');
            input.readOnly = input.value.trim() !== '';
        }

        // 页面加载完成后检查一次
        document.addEventListener('DOMContentLoaded', toggleReadOnly);
        // 输入过程中实时更新
        {#document.getElementById('id_name').addEventListener('input', toggleDisable);#}
    </script>
{% endblock %}

app01/templates/agent_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-default" href="/agent/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true" style="margin-right: 5px"></span>
                新建Agent
            </a>
        </div>
        <div>
            <div class="bs-example" data-example-id="panel-without-body-with-table">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true" style="margin-right: 5px"></span>
                        Agent列表
                    </div>

                    <!-- Table -->
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>编号</th>
                            <th>名称</th>
                            <th>简介</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for obj in queryset %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ obj.name }}</td>
                                <th>{{ obj.description }}</th>
                                <td>
                                    <a class="btn btn-default btn-xs" href="/agent/{{ obj.id }}/edit">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"
                                              style="margin-right: 3px"></span>
                                        编辑
                                    </a>
                                    <a class="btn btn-default btn-xs" href="/agent/delete?nid={{ obj.id }}">
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"
                                              style="margin-right: 3px"></span>
                                        删除
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static 'img/bitbug_favicon.ico' %}">
    <title>用户登录</title>
    <link href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}" rel="stylesheet">
    <style>
        .bigone {
            height: 660px;
            background-image: url("{% static 'img/JTBD_1.png' %}");
            background-position: top center;
            background-size: 960px auto;
            background-repeat: no-repeat;
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
        }
        .opening {
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            align-items: center;
            height: 100px;
            font-size: 12px;
            color: gray;
        }
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 6px;
            box-shadow: 5px 5px 20px #aaaaaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            padding: 20px 40px;
        }

        .account h1 {
            text-align: center;
            margin-top: 10px;
        }

        .captcha-img {
            cursor: pointer;
            height: 40px;
            border: 1px solid #ccc;
        }

        form {
            position: relative;
            {#padding-bottom: 2.5rem;#}
        }

        form > a {
            position: absolute;
            bottom: 0;
            right: 0;
            {#transform: translateX(-100%);#}
        }
    </style>
</head>
<div>
    <div class="opening">
        <p>阿里的客服健身，阿顺利的客服接阿上；阿拉的客服接撒；否啊；收到了看法；收到了客服接阿</p>
    </div>
    <div class="bigone">
        <div class="account">
            <h1>用户登录</h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>用户名</label>
                    {{ form.username }}
                    <span style="color: red">{{ form.username.errors }}</span>
                </div>
                <div class="form-group">
                    <label>密码</label>
                    {{ form.password }}
                    <span style="color: red">{{ form.password.errors }}</span>
                </div>
                <div class="form-group">
                    <label>验证码</label>
                    <div class="row">
                        <div class="col-md-7">
                            {{ form.captcha }}
                            <span style="color: red">{{ form.captcha.errors }}</span>
                        </div>
                        <div class="col-md-5">
                            <img class="captcha-img" src="{% url 'captcha' %}">
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">登 录</button>
                <a href="/register/">注 册</a>
            </form>

        </div>
    </div>
</div>
<script>
    document.querySelector('.captcha-img').onclick = function () {
        this.src = "{% url 'captcha' %}?t=" + Date.now();
    };
    document.querySelector('#id_captcha').addEventListener('keydown', function (e) {
        if (e.key === 'Enter') {
            e.preventDefault();
            document.querySelector('.captcha-img').click();
        }
    });
</script>
</body>
</html>

app01/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static 'img/bitbug_favicon.ico' %}">
    <title>用户登录</title>
    <link href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}" rel="stylesheet">
    <style>
        .bigone {
            height: 720px;
            background-image: url("{% static 'img/JTBD_2.png' %}");
            background-position: top center;
            background-size: 960px auto;
            background-repeat: no-repeat;
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
        }
        .opening {
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            align-items: center;
            height: 100px;
            font-size: 12px;
            color: gray;
        }
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 6px;
            box-shadow: 5px 5px 20px #aaaaaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            padding: 20px 40px;
        }

        .account h1 {
            text-align: center;
            margin-top: 10px;
        }

        .captcha-img {
            cursor: pointer;
            height: 40px;
            border: 1px solid #ccc;
        }

        form {
            position: relative;
            {#padding-bottom: 2.5rem;#}
        }

        form > a {
            position: absolute;
            bottom: 0;
            right: 0;
            {#transform: translateX(-100%);#}
        }
    </style>
</head>
<div>
    <div class="opening">
        <p>阿里的客服健身，阿顺利的客服接阿上；阿拉的客服接撒；否啊；收到了看法；收到了客服接阿</p>
    </div>
    <div class="bigone">
        <div class="account">
            <h1>用户注册</h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>用户名</label>
                    {{ form.username }}
                    <span style="color: red">{{ form.username.errors }}</span>
                </div>
                <div class="form-group">
                    <label>密码</label>
                    {{ form.password }}
                    <span style="color: red">{{ form.password.errors }}</span>
                </div>
                <div class="form-group">
                    <label>确认密码</label>
                    {{ form.password2 }}
                    <span style="color: red">{{ form.password2.errors }}</span>
                </div>
                <div class="form-group">
                    <label>验证码</label>
                    <div class="row">
                        <div class="col-md-7">
                            {{ form.captcha }}
                            <span style="color: red">{{ form.captcha.errors }}</span>
                        </div>
                        <div class="col-md-5">
                            <img class="captcha-img" src="{% url 'captcha' %}">
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">注 册</button>
                <a href="/login/">登 录</a>
            </form>

        </div>
    </div>
</div>
<script>
    document.querySelector('.captcha-img').onclick = function () {
        this.src = "{% url 'captcha' %}?t=" + Date.now();
    };
    document.querySelector('#id_captcha').addEventListener('keydown', function (e) {
        if (e.key === 'Enter') {
            e.preventDefault();
            document.querySelector('.captcha-img').click();
        }
    });
</script>
</body>
</html>